# Generated by Django 4.1 on 2022-08-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('grade', models.IntegerField(default=0)),
                ('specialty', models.CharField(max_length=200)),
                ('salary', models.IntegerField(default=0)),
                ('education', models.CharField(max_length=300)),
                ('experience', models.TextField()),
                ('portfolio', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
